# Start with a base image that has Java installed
FROM openjdk:17-jdk-alpine

#Create directory
RUN mkdir -p /home/app

# Set the working directory inside the container
WORKDIR /home/app

# Copy the JAR file generated by Maven into the Docker image
COPY ./target/userInfo-0.0.1-SNAPSHOT.jar /home/app/my-springboot-app.jar

# Expose the application's port
EXPOSE 8080

# Define the command to run the application
ENTRYPOINT ["java", "-jar", "my-springboot-app.jar"]